<div class="container">
    <h1>login</h1>
    <form id="login" data-controller="user">
        <div class="form-group">
            <label for=""></label>
            <input type="text" class="form-control" name="user_email" id="" aria-describedby="helpId" placeholder="">
            <small id="helpId" class="form-text text-muted">Help text</small>
        </div>
        <div class="form-group">
          <label for=""></label>
          <input type="password" class="form-control" name="user_password" id="" placeholder="">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
