<header class="mdl-layout__header ">
  <div class="mdl-layout__header-row">
    <!-- Title -->
    <span class="mdl-layout-title">Project</span>
    <!-- Add spacer, to align navigation to the right -->
    <div class="mdl-layout-spacer"></div>
    <!-- Navigation -->
    <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="<?=URL?>">Link</a>
        <a class="mdl-navigation__link" href="<?=URL?>">Link</a>
        <a class="mdl-navigation__link" href="<?=URL?>">Link</a>
        <a class="mdl-navigation__link" href="<?=URL?>">Link</a>
    </nav>
  </div>
</header>
<div class="mdl-layout__drawer">
  <span class="mdl-layout-title"><?= @$_SESSION['user'] ?></span>
  <nav class="mdl-navigation">
    <a class="mdl-navigation__link" href="<?=URL?>">Link</a>
    <a class="mdl-navigation__link" href="<?=URL?>">Link</a>
    <a class="mdl-navigation__link" href="<?=URL?>">Link</a>
  </nav>
</div>